In [7]:
import pandas as pd

In [ ]:
df = pd.read_csv("/home/elmasny/Documents/covid_pipeline/data/dataset.csvdd")

In [9]:
df.info

<bound method DataFrame.info of       FIPS Admin2    Province_State  Country_Region          Last_Update  \
0      NaN    NaN               NaN     Afghanistan  2021-01-02 05:22:33
1      NaN    NaN               NaN         Albania  2021-01-02 05:22:33
2      NaN    NaN               NaN         Algeria  2021-01-02 05:22:33
3      NaN    NaN               NaN         Andorra  2021-01-02 05:22:33
4      NaN    NaN               NaN          Angola  2021-01-02 05:22:33
...    ...    ...               ...             ...                  ...
4006   NaN    NaN           Unknown         Ukraine  2021-01-02 05:22:33
4007   NaN    NaN               NaN           Nauru  2021-01-02 05:22:33
4008   NaN    NaN              Niue     New Zealand  2021-01-02 05:22:33
4009   NaN    NaN               NaN          Tuvalu  2021-01-02 05:22:33
4010   NaN    NaN  Pitcairn Islands  United Kingdom  2021-01-02 05:22:33

           Lat       Long_  Confirmed  Deaths  Recovered  Active  \
0     33.93911   67.709953      52513    2201      41727    8585
1     41.15330   20.168300      58316    1181      33634   23501
2     28.03390    1.659600      99897    2762      67395   29740
3     42.50630    1.521800       8117      84       7463     570
4    -11.20270   17.873900      17568     405      11146    6017
...        ...         ...        ...     ...        ...     ...
4006       NaN         NaN          0       0          0       0
4007  -0.52280  166.931500          0       0          0       0
4008 -19.05440 -169.867200          0       0          0       0
4009  -7.10950  177.649300          0       0          0       0
4010 -24.37680 -128.324200          0       0          0       0

                          Combined_Key  Incident_Rate  Case_Fatality_Ratio
0                          Afghanistan     134.896578             4.191343
1                              Albania    2026.409062             2.025173
2                              Algeria     227.809861             2.764848
3                              Andorra   10505.403482             1.034865
4                               Angola      53.452981             2.305328
...                                ...            ...                  ...
4006                  Unknown, Ukraine       0.000000             0.000000
4007                             Nauru       0.000000             0.000000
4008                 Niue, New Zealand       0.000000             0.000000
4009                            Tuvalu       0.000000             0.000000
4010  Pitcairn Islands, United Kingdom       0.000000             0.000000

[4011 rows x 14 columns]>

In [10]:
df['Last_Update'] = pd.to_datetime(df['Last_Update'], errors='coerce')
df['Last_Update'] = df['Last_Update'].dt.strftime('%Y-%m-%d')

In [11]:
df

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-02,33.93911,67.709953,52513,2201,41727,8585,Afghanistan,134.896578,4.191343
1,NaN,NaN,NaN,Albania,2021-01-02,41.15330,20.168300,58316,1181,33634,23501,Albania,2026.409062,2.025173
2,NaN,NaN,NaN,Algeria,2021-01-02,28.03390,1.659600,99897,2762,67395,29740,Algeria,227.809861,2.764848
3,NaN,NaN,NaN,Andorra,2021-01-02,42.50630,1.521800,8117,84,7463,570,Andorra,10505.403482,1.034865
4,NaN,NaN,NaN,Angola,2021-01-02,-11.20270,17.873900,17568,405,11146,6017,Angola,53.452981,2.305328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4006,NaN,NaN,Unknown,Ukraine,2021-01-02,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4007,NaN,NaN,NaN,Nauru,2021-01-02,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4008,NaN,NaN,Niue,New Zealand,2021-01-02,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4009,NaN,NaN,NaN,Tuvalu,2021-01-02,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4010,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-02,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

In [12]:
df['Country_Region'].value_counts()

Country_Region
US                      3276
Russia                    83
Japan                     49
India                     37
China                     34
                        ...
Winter Olympics 2022       1
Antarctica                 1
Korea, North               1
Nauru                      1
Tuvalu                     1
Name: count, Length: 200, dtype: int64

In [13]:
 location_mapping = {
            'US': 'United States',
            'UK': 'United Kingdom',
            'Korea, South': 'South Korea',
            'Taiwan*': 'Taiwan',
            'Korea, North': 'North Korea'
        }

 df['Country_Region'] = df['Country_Region'].replace(location_mapping)

In [14]:
df

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-02,33.93911,67.709953,52513,2201,41727,8585,Afghanistan,134.896578,4.191343
1,NaN,NaN,NaN,Albania,2021-01-02,41.15330,20.168300,58316,1181,33634,23501,Albania,2026.409062,2.025173
2,NaN,NaN,NaN,Algeria,2021-01-02,28.03390,1.659600,99897,2762,67395,29740,Algeria,227.809861,2.764848
3,NaN,NaN,NaN,Andorra,2021-01-02,42.50630,1.521800,8117,84,7463,570,Andorra,10505.403482,1.034865
4,NaN,NaN,NaN,Angola,2021-01-02,-11.20270,17.873900,17568,405,11146,6017,Angola,53.452981,2.305328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4006,NaN,NaN,Unknown,Ukraine,2021-01-02,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4007,NaN,NaN,NaN,Nauru,2021-01-02,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4008,NaN,NaN,Niue,New Zealand,2021-01-02,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4009,NaN,NaN,NaN,Tuvalu,2021-01-02,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4010,NaN,NaN,Pitcairn Islands,United Kingdom,2021-01-02,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

In [15]:
df.isna().sum() / 100

FIPS                   7.46
Admin2                 7.41
Province_State         1.78
Country_Region         0.00
Last_Update            0.00
Lat                    0.89
Long_                  0.89
Confirmed              0.00
Deaths                 0.00
Recovered              0.00
Active                 0.00
Combined_Key           0.00
Incident_Rate          0.89
Case_Fatality_Ratio    0.48
dtype: float64

In [16]:
df.Province_State

0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
              ...
4006             Unknown
4007                 NaN
4008                Niue
4009                 NaN
4010    Pitcairn Islands
Name: Province_State, Length: 4011, dtype: object

In [17]:
df.drop(['FIPS','Admin2','Province_State'],axis = 1 ,inplace = True)

In [18]:
df

,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,Afghanistan,2021-01-02,33.93911,67.709953,52513,2201,41727,8585,Afghanistan,134.896578,4.191343
1,Albania,2021-01-02,41.15330,20.168300,58316,1181,33634,23501,Albania,2026.409062,2.025173
2,Algeria,2021-01-02,28.03390,1.659600,99897,2762,67395,29740,Algeria,227.809861,2.764848
3,Andorra,2021-01-02,42.50630,1.521800,8117,84,7463,570,Andorra,10505.403482,1.034865
4,Angola,2021-01-02,-11.20270,17.873900,17568,405,11146,6017,Angola,53.452981,2.305328
...,...,...,...,...,...,...,...,...,...,...,...
4006,Ukraine,2021-01-02,NaN,NaN,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4007,Nauru,2021-01-02,-0.52280,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4008,New Zealand,2021-01-02,-19.05440,-169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4009,Tuvalu,2021-01-02,-7.10950,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4010,United Kingdom,2021-01-02,-24.37680,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

In [19]:
numerical_cols = df.select_dtypes(include='number')

In [20]:
(numerical_cols< 0).any()

Lat                     True
Long_                   True
Confirmed              False
Deaths                 False
Recovered              False
Active                 False
Incident_Rate          False
Case_Fatality_Ratio    False
dtype: bool

In [21]:
df['Long_'] = df['Long_'].abs()

In [22]:
df.fillna(numerical_cols.mean(), inplace=True)

In [23]:
df.isna().sum() / 100

Country_Region         0.0
Last_Update            0.0
Lat                    0.0
Long_                  0.0
Confirmed              0.0
Deaths                 0.0
Recovered              0.0
Active                 0.0
Combined_Key           0.0
Incident_Rate          0.0
Case_Fatality_Ratio    0.0
dtype: float64

In [24]:
df

,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,Afghanistan,2021-01-02,33.939110,67.709953,52513,2201,41727,8585,Afghanistan,134.896578,4.191343
1,Albania,2021-01-02,41.153300,20.168300,58316,1181,33634,23501,Albania,2026.409062,2.025173
2,Algeria,2021-01-02,28.033900,1.659600,99897,2762,67395,29740,Algeria,227.809861,2.764848
3,Andorra,2021-01-02,42.506300,1.521800,8117,84,7463,570,Andorra,10505.403482,1.034865
4,Angola,2021-01-02,-11.202700,17.873900,17568,405,11146,6017,Angola,53.452981,2.305328
...,...,...,...,...,...,...,...,...,...,...,...
4006,Ukraine,2021-01-02,35.768908,-71.113714,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4007,Nauru,2021-01-02,-0.522800,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4008,New Zealand,2021-01-02,-19.054400,169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4009,Tuvalu,2021-01-02,-7.109500,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4010,United Kingdom,2021-01-02,-24.376800,128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000

In [26]:
 cleaned_data = df.copy()

In [27]:
cleaned_data

,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,Afghanistan,2021-01-02,33.939110,67.709953,52513,2201,41727,8585,Afghanistan,134.896578,4.191343
1,Albania,2021-01-02,41.153300,20.168300,58316,1181,33634,23501,Albania,2026.409062,2.025173
2,Algeria,2021-01-02,28.033900,1.659600,99897,2762,67395,29740,Algeria,227.809861,2.764848
3,Andorra,2021-01-02,42.506300,1.521800,8117,84,7463,570,Andorra,10505.403482,1.034865
4,Angola,2021-01-02,-11.202700,17.873900,17568,405,11146,6017,Angola,53.452981,2.305328
...,...,...,...,...,...,...,...,...,...,...,...
4006,Ukraine,2021-01-02,35.768908,-71.113714,0,0,0,0,"Unknown, Ukraine",0.000000,0.000000
4007,Nauru,2021-01-02,-0.522800,166.931500,0,0,0,0,Nauru,0.000000,0.000000
4008,New Zealand,2021-01-02,-19.054400,169.867200,0,0,0,0,"Niue, New Zealand",0.000000,0.000000
4009,Tuvalu,2021-01-02,-7.109500,177.649300,0,0,0,0,Tuvalu,0.000000,0.000000
4010,United Kingdom,2021-01-02,-24.376800,128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom",0.000000,0.000000